services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        container_name: wizardForm_nginx
        depends_on:
            -   app

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   mysql
        container_name: wizardForm_app

    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wizardForm
            MYSQL_ROOT_PASSWORD: root
        container_name: wizardForm_mysql


