services:
    nginx:
        container_name: wizardForm_nginx
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        depends_on:
            -   app

    app:
        container_name: wizardForm_app
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        command: >
            sh -c "chown -R www-data:www-data storage bootstrap/cache && php-fpm"
        depends_on:
            -   mysql
        env_file:
            - .env
        environment:
            PHP_IDE_CONFIG: "serverName=wizardForm"

    mysql:
        container_name: wizardForm_mysql
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wizardForm
            MYSQL_ROOT_PASSWORD: root

    redis:
        container_name: wizardForm_redis
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - ./docker/redis:/data
