services:
    nginx:
        container_name: wizardForm_nginx
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"

        depends_on:
            -   app

    app:
        container_name: wizardForm_app
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
        depends_on:
            -   mysql
        environment:
            PHP_IDE_CONFIG: "serverName=wizardForm"


    mysql:
        container_name: wizardForm_mysql
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: wizardForm
            MYSQL_ROOT_PASSWORD: root



